
package Vista;

import Modelo.Alojamiento;
import Persistencia.alojamientoData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class Alojamientos extends javax.swing.JInternalFrame { 
    private alojamientoData alojaData;
    private ArrayList <Alojamiento> listaAloja;
    private DefaultTableModel modelo;
    
    public Alojamientos() {
        initComponents();
        alojaData = new alojamientoData();
        listaAloja = (ArrayList <Alojamiento>)alojaData.listarAlojamiento();
        modelo = new DefaultTableModel();
        comboAlojamiento();
       armarCabeceraTabla();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlojamiento = new javax.swing.JDesktopPane();
        jlbAlojamiento = new javax.swing.JLabel();
        comboAlojamientos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbMostarAlojamientos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAlojamiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbAlojamiento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlbAlojamiento.setForeground(new java.awt.Color(51, 153, 255));
        jlbAlojamiento.setText("Alojamiento");
        panelAlojamiento.add(jlbAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        panelAlojamiento.add(comboAlojamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 65, 252, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Alojamientos:");
        panelAlojamiento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 63, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelAlojamiento.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 371, -1, -1));

        btnAlta.setText("Alta");
        panelAlojamiento.add(btnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 371, -1, -1));

        btnBaja.setText("Baja");
        panelAlojamiento.add(btnBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 371, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelAlojamiento.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 371, -1, -1));

        jtbMostarAlojamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbMostarAlojamientos);

        panelAlojamiento.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 132, 487, 233));

        btnEliminar.setText("Eliminar");
        panelAlojamiento.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 371, -1, -1));

        getContentPane().add(panelAlojamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 600, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Alojamiento> comboAlojamientos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbAlojamiento;
    private javax.swing.JTable jtbMostarAlojamientos;
    private javax.swing.JDesktopPane panelAlojamiento;
    // End of variables declaration//GEN-END:variables

    private void comboAlojamiento() {
     for (Alojamiento item : listaAloja);  {
        //comboAlojamientos.addItem(item);
    }
    }

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Nombre");
        filaCabecera.add("Capacidad");
        filaCabecera.add("nroAmbientes");
        filaCabecera.add("camas");
        filaCabecera.add("baños");
        filaCabecera.add("precioNoche");
        
        for (Object it: filaCabecera) {
        modelo.addColumn(it);
    }
        jtbMostarAlojamientos.setModel(modelo);
    
    }
    private void borrarFilasdeTabla () {
        int indice = modelo.getRowCount() -1;
        for (int i = indice ; i>=0;i--){
            modelo.removeRow(i);
        }
    }
    private void cargarMateriasInscriptas (){
        Alojamiento selec = (Alojamiento) comboAlojamientos.getSelectedItem();
       List <Alojamiento> lista = alojaData.listarAlojamiento();
       for (Alojamiento a : lista){
           modelo.addRow(new Object [] {a.getNombre(),a.getCapacidad(),a.getCapacidad(),a.getNroAmbientes(),a.getCamas(),a.getBaños(),a.getPrecioNoche()});
    }    
}
}